name: Build Production Branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Change Directory
      run: |
        cd UdemyBluetooth

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      working-directory: ./UdemyBluetooth
      run: dotnet restore UdemyBluetooth.sln

    - name: Build
      run: |
        cd UdemyBluetooth |
        dotnet publish UdemyBluetooth.csproj -f net7.0-android -c Debug
